Milestone: Views
tresorsawasawa/blog_app pull request #7
Opened 2022-05-19 23:00 UTC by tresorsawasawa

In this PR, I completed the following tasks:
- [ ] Implemented the design from the sneak peek wireframes.
- [ ] Used methods that I have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
- [ ] Implemented index and show function in User and Post controller
- [ ] Used partials

2022-05-19 23:41 UTC, andersonlebon requested changes
## Hi @tresorsawasawa 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-19 23:41 UTC, andersonlebon commented on app/views/posts/index.html.erb
> +      <%= render partial: "post", locals: { post: post } %>
- [ ] KIndly make sure when I click on the post, it should bring me to the `post#show` page.

2022-05-19 23:41 UTC, andersonlebon commented on app/views/users/index.html.erb
> +    <%= render partial: 'user', locals: {user: user} %>
![image](https://user-images.githubusercontent.com/65068771/169421137-6f38fd3b-6925-4b78-8a5f-2b937edd72dc.png)


- [ ] kindly make sure when I click on the user it should bring me to the `user#show` template/view

2022-05-20 00:38 UTC, tresorsawasawa commented
Hey @andersonlebon 

Thank You for the review :pray: 
![Thank You](https://mrautomaticcharismatic.files.wordpress.com/2016/07/thankyou.gif?w=490)
I really appreciate :+1: :+1:

2022-05-20 01:06 UTC, andersonlebon approved these changes
## Hi @tresorsawasawa 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-20 01:09 UTC, tresorsawasawa commented
Hey @andersonlebon

Thank You for the review :pray: 
![Thank You](https://mrautomaticcharismatic.files.wordpress.com/2016/07/thankyou.gif?w=490)
I really appreciate :+1: :+1:

2022-05-20 01:09 UTC, merged